/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART.h"
#include "isr_uart_rx.h"
#include "pin_enable_4_aliases.h"
#include "pin_enable_4.h"
#include "pin_enable_3_aliases.h"
#include "pin_enable_3.h"
#include "pin_enable_1_aliases.h"
#include "pin_enable_1.h"
#include "pin_enable_2_aliases.h"
#include "pin_enable_2.h"
#include "isr_detection.h"
#include "Pin_1_aliases.h"
#include "Pin_1.h"
#include "Motor_Reg_2.h"
#include "timer_clock.h"
#include "Motor_Timer.h"
#include "isr_timer.h"
#include "Interrupt_aliases.h"
#include "Interrupt.h"
#include "SDA_1_aliases.h"
#include "SDA_1.h"
#include "SCL_1_aliases.h"
#include "SCL_1.h"
#include "Clock_1.h"
#include "I2C.h"
#include "I2C_PVT.h"
#include "PhotoDiode_aliases.h"
#include "PhotoDiode.h"
#include "Sample_Hold_1.h"
#include "ADC_DelSig_1.h"
#include "PWM_1.h"
#include "Clock_2.h"
#include "IR_puls_aliases.h"
#include "IR_puls.h"
#include "pin_full_aliases.h"
#include "pin_full.h"
#include "pin_empty_aliases.h"
#include "pin_empty.h"
#include "pin_enable_5_aliases.h"
#include "pin_enable_5.h"
#include "pin_enable_6_aliases.h"
#include "pin_enable_6.h"
#include "pin_enable_8_aliases.h"
#include "pin_enable_8.h"
#include "pin_enable_7_aliases.h"
#include "pin_enable_7.h"
#include "Motor_Reg_1.h"
#include "UART_IntClock.h"
#include "ADC_DelSig_1_AMux.h"
#include "ADC_DelSig_1_Ext_CP_Clk.h"
#include "ADC_DelSig_1_IRQ.h"
#include "ADC_DelSig_1_theACLK.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

